app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core.homepage.views import IndexView
from django.conf.urls import handler400
from core.erp.views.dashboard.views import page_not_found404

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('login/', include('core.login.urls')),
    path('user/', include('core.user.urls')),
    path('erp/', include('core.erp.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/core/erp/urls.py
from django.urls import path
from core.erp.views.padron.views import *
from core.erp.views.dninoexist.views import *
from core.erp.views.dashboard.views import *

app_name = 'app'

urlpatterns = [
    # PADRON
    path('padron/list/', PadronListView.as_view(), name='padron_list'),
    path('padron/update/<int:pk>/', PadronUpdateView.as_view(), name='padron_update'),
    path('padron/dniupdate/', PadronDNIUpdateView.as_view(), name='padron_dniupdate'),
    path('padron/mesaupdate/', PadronMesaDNIUpdateView.as_view(), name='padron_tableupdate'),

    # DNI no Existen
    path('dninoexist/list/', DniNoExistListView.as_view(), name='dninoexist_list'),
    path('dninoexist/create/', DniNoExistCreateView.as_view(), name='dninoexist_create'),
    path('dninoexist/update/<int:pk>/', DniNoExistUpdateView.as_view(), name='dninoexist_update'),
    path('dninoexist/delete/<int:pk>/', DniNoExistDeleteView.as_view(), name='dninoexist_delete'),

    # PANEL DASHBOARD
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
]

app/core/erp/models.py
from django.db import models
from django.forms import model_to_dict

# Create your models here.
class Padron(models.Model):
    dni = models.IntegerField(blank=True, null=True, verbose_name='DNI')
    apellido = models.CharField(max_length=255, blank=True, null=True, verbose_name='Apellido')
    nombre = models.CharField(max_length=255, blank=True, null=True, verbose_name='Nombres')
    domicilio = models.CharField(max_length=255, blank=True, null=True, verbose_name='Domicilio')
    departamento = models.CharField(max_length=255, blank=True, null=True, verbose_name='Departamento')
    nombre_circuito = models.CharField(max_length=255, blank=True, null=True, verbose_name='Nombre Circuito')
    codigo_circuito = models.CharField(max_length=10, blank=True, null=True, verbose_name='Código Circuito')
    mesa = models.IntegerField(blank=True, null=True, verbose_name='Número Mesa')
    voto = models.SmallIntegerField(default=1, blank=True, null=True, verbose_name='Votó')

    def __str__(self):
        return self.dni

    def toJSON(self):
        item = model_to_dict(self)
        return item

    class Meta:
        db_table = 'padron'
        ordering = ['id']


class DniNoExist(models.Model):
    num_distrito = models.CharField(max_length=5, blank=False, null=False, verbose_name='Número Distrito')
    num_circuito = models.CharField(max_length=5, blank=False, null=False, verbose_name='Número Circuito')
    num_mesa = models.CharField(max_length=3, blank=False, null=False, verbose_name='Número Mesa')
    num_orden = models.CharField(max_length=4, blank=False, null=False, verbose_name='Número Orden')
    dni = models.CharField(max_length=10, blank=False, null=False, unique=True, verbose_name='DNI')
    apellido = models.CharField(max_length=255, blank=True, null=True, verbose_name='Apellido')
    nombre = models.CharField(max_length=255, blank=True, null=True, verbose_name='Nombre')

    def __str__(self):
        return self.dni

    def toJSON(self):
        item = model_to_dict(self)
        return item

    class Meta:
        db_table = 'dninoexist'
        ordering = ['id']



# circuito = models.CharField(max_length=8, blank=True, null=True, verbose_name='Nombre Circuito')
# nombre_circuito = models.CharField(max_length=255, blank=True, null=True, verbose_name='Nombre Circuito')

app/core/erp/views/dashboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse_lazy
from django.shortcuts import render


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        request.user.get_group_session()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['title'] = 'Reporte de ventas anual'
        context['list_url'] = reverse_lazy('app:padron_list')
        context['padron_url'] = reverse_lazy('app:padron_list')
        context['dni_no_url'] = reverse_lazy('app:dninoexist_list')
        context['padron_dni_update'] = reverse_lazy('app:padron_dniupdate')
        return context


# Paginas de ERRORES
def page_not_found404(request, exception):
    return render(request,'404.html')

app/core/erp/views/dninoexist/views.py
import json
import os
from django.contrib.auth.mixins import LoginRequiredMixin
from core.erp.mixins import ValidatePermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
# from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from core.erp.models import DniNoExist
from core.erp.forms import DniNoExistModelForm


class DniNoExistListView(LoginRequiredMixin, ListView):
    model = DniNoExist
    template_name = 'dninoexist/list.html'
    permission_required = 'view_dninoexist'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for i in DniNoExist.objects.all():
                    data.append(i.toJSON())
            else:
                data['error'] = 'Ha ocurrido un Error. No se pudo realizar la solicitud'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado DNI No Encontrado'
        context['create_url'] = reverse_lazy('app:dninoexist_create')
        context['list_url'] = reverse_lazy('app:dninoexist_list')
        context['padron_url'] = reverse_lazy('app:padron_list')
        context['dni_no_url'] = reverse_lazy('app:dninoexist_list')
        context['padron_dni_update'] = reverse_lazy('app:padron_dniupdate')
        context['padron_update'] = reverse_lazy('app:padron_dniupdate')
        return context


class DniNoExistCreateView(LoginRequiredMixin, CreateView):
    model = DniNoExist
    form_class = DniNoExistModelForm
    template_name = 'dninoexist/create.html'
    success_url = reverse_lazy('app:dninoexist_list')
    permission_required = 'add_dninoexist'

    # @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'create':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No se pudo realizar la solicitud'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Crear DNI No Encontrado'
        context['padron_url'] = reverse_lazy('app:padron_list')
        context['dni_no_url'] = reverse_lazy('app:dninoexist_list')
        context['padron_dni_update'] = reverse_lazy('app:padron_dniupdate')
        context['list_url'] = reverse_lazy('app:dninoexist_list')
        context['action'] = 'create'
        return context


class DniNoExistUpdateView(LoginRequiredMixin, UpdateView):
    model = DniNoExist
    form_class = DniNoExistModelForm
    template_name = 'dninoexist/create.html'
    success_url = reverse_lazy('app:dninoexist_list')
    url_redirect = success_url
    permission_required = 'change_dninoexist'

    # @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'update':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No se pudo realizar la solicitud'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar DNI No Encontrado'
        context['padron_url'] = reverse_lazy('app:padron_list')
        context['dni_no_url'] = reverse_lazy('app:dninoexist_list')
        context['padron_dni_update'] = reverse_lazy('app:padron_dniupdate')
        context['action'] = 'update'
        context['list_url'] = self.success_url
        return context


class DniNoExistDeleteView(LoginRequiredMixin, DeleteView):
    model = DniNoExist
    template_name = 'dninoexist/delete.html'
    success_url = reverse_lazy('app:dninoexist_list')
    url_redirect = success_url
    permission_required = 'delete_dninoexist'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            self.object.delete()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Eliminar Registro'
        context['padron_url'] = reverse_lazy('app:padron_list')
        context['dni_no_url'] = reverse_lazy('app:dninoexist_list')
        context['padron_dni_update'] = reverse_lazy('app:padron_dniupdate')
        # context['action'] = 'delete'
        context['list_url'] = self.success_url
        return context

app/core/erp/templates/padron/create.html
{% extends 'create.html' %}

app/core/erp/templates/padron/dniupdate.html
{% extends 'body.html' %}

{% load static %}

{% load widget_tweaks %}

<!-- Extra Head -->
{% block head_extra %}
    <!-- AutoComplete -->
    <link rel="stylesheet" href="{% static 'librery/select2-4.1.0/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'librery/select2-4.1.0/css/select2.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'librery/select2-4.1.0/css/select2-bootstrap4.min.css' %}"/>
    <script src="{% static 'librery/select2-4.1.0/js/select2.min.js' %}"></script>
    <script src="{% static 'librery/select2-4.1.0/js/i18n/es.js' %}"></script>
    <!-- ./AutoComplete Select2 -->
    <!-- JavaScript extra -->
    <script src="{% static 'padron/js/dniupdate.js' %}"></script>
    <!-- JavaScript extra -->
{% endblock %}
<!-- ./Extra Head -->

<!-- Data Body -->
{% block data_body %}
    <!-- Card Header -->
    <form method="POST" action="." id="FormCreate" enctype="multipart/form-data">
        <div class="card-header card-primary card-outline">
            <h3 class="card-title">
                <i class="fa-solid fa-rotate"></i> {{ title }}
            </h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <!-- ./Card Header -->
        <!-- Card Body -->
        <div class="card-body">
            {% csrf_token %}
            <input type="hidden" name="action" value="{{ action }}">
            {% if form.errors %}
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="fa-solid fa-triangle-exclamation"></i> ! Ha ocurrido un ERROR !</h5>
                    <ul>
                        {% for field in form %}
                            {% for error in form %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

            <div class="row">
                <div class="col-lg-3">
                    <div class="input-group mb-3">

                        {#                        <select id="search_dni" name="dni" type="text" class="form-control select2-blue"#}
                        {#                                aria-label="Ingrese DNI" aria-describedby="button-addon2"></select>#}
                        {##}
                        {#                        <button style="background-color:var(--green05); Font-size: 12px"#}
                        {#                                class="btn text-white btnUpdateDNI btnUpdateDNIKeyup" type="submit"><i#}
                        {#                                class="fa-solid fa-rotate" autofocus></i> Actualizar#}
                        {#                        </button>#}

                        <input id="id_search" name="search" type="text" class="form-control select2-blue"
                               placeholder="Ingrese N° de DNI..."
                               aria-label="search_product" aria-describedby="button-addon2" autocomplete="off" minlength="5" maxlength="8">
                        <button style="background-color:var(--blue02); Font-size: 12px"
                                class="btn text-white btnSearchProduct" id="id_btnSearchProduct"
                                name="btnSearchProduct">
                            <i class="fa-solid fa-magnifying-glass"></i> Buscar
                        </button>

                    </div>

                    <div class="form-outline">
                        <input id="id" name="id" type="number" style="display:none;" class="form-control"
                               aria-label="id"
                               aria-describedby="addon-wrapping">
                    </div>
                </div>
                <div class="col-lg-9"></div>
            </div>

            <hr>

            <div class="row mb-4">
                <div class="col">
                    <div class="form-outline">
                        <label class="form-label">DNI</label>
                        <input id="id_dni" type="text" class="form-control" readonly aria-label="dni"
                               aria-describedby="addon-wrapping">
                    </div>
                </div>
                <div class="col">
                    <div class="form-outline">
                        <label class="form-label">Apellido</label>
                        <input id="apellido" type="text" class="form-control" readonly aria-label="surname"
                               aria-describedby="addon-wrapping">
                    </div>
                </div>
                <div class="col">
                    <div class="form-outline">
                        <label class="form-label">Nombre</label>
                        <input id="nombre" type="text" class="form-control" readonly aria-label="name"
                               aria-describedby="addon-wrapping">
                    </div>
                </div>

            </div>


            <div class="row mb-4">
                <div class="col">
                    <div class="form-outline">
                        <span class="form-label">Votó</span>
                        <input id="voto" name="voto" type="text" class="form-control" readonly aria-label="address"
                               aria-describedby="addon-wrapping">

                        <input id="voto_invalid" type="text" class="form-control is-invalid" readonly
                               aria-label="address"
                               aria-describedby="addon-wrapping">

                        <input id="voto_valid" type="text" class="form-control is-valid" readonly aria-label="address"
                               aria-describedby="addon-wrapping">
                    </div>
                </div>
                <div class="col">
                    <div class="form-outline">
                        <span class="form-label">Domicilio</span>
                        <input id="domicilio" type="text" class="form-control" readonly aria-label="address"
                               aria-describedby="addon-wrapping">
                    </div>
                </div>
                <div class="col">
                    <div class="form-outline">
                        <span class="form-label">Departamento</span>
                        <input id="departamento" type="text" class="form-control" readonly aria-label="department"
                               aria-describedby="addon-wrapping">
                    </div>
                </div>
                <div class="col">
                    <div class="form-outline">
                        <span class="form-label">Nombre Circuito</span>
                        <input id="nombre_circuito" type="text" class="form-control" readonly aria-label="circuit"
                               aria-describedby="addon-wrapping">
                    </div>
                </div>
                <div class="col">
                    <div class="form-outline">
                        <span class="form-label">Código Circuito</span>
                        <input id="codigo_circuito" type="text" class="form-control" readonly
                               aria-label="circuit number"
                               aria-describedby="addon-wrapping">
                    </div>
                </div>
                <div class="col">
                    <div class="form-outline">
                        <span class="form-label">Mesa</span>
                        <input id="mesa" type="text" class="form-control" readonly aria-label="circuit number"
                               aria-describedby="addon-wrapping">
                    </div>
                </div>
            </div>
        </div>
        <!-- ./Card Body -->
        <!-- Card Footer-Buttons -->
        <div class="card-footer text-center">
            <button style="background-color:var(--green05); FONT-SIZE: 9pt"
                    class="btn text-white btn-rounded btnUpdateDNI btnUpdateDNIKeyup" type="submit">
                <i class="fa-solid fa-rotate"></i> Actualizar
            </button>
            <button type="button" id="cleaninputdni" style="background-color:var(--orange01); FONT-SIZE: 9pt"
                    class="btn text-white btn-rounded">
                <i class="fa-solid fa-trash-can"></i> Limpar
            </button>
            <a href="{% url 'app:padron_list' %}" style="background-color:var(--red06); FONT-SIZE: 9pt"
               class="btn text-white btn-rounded">
                <i class="fa-solid fa-xmark"></i> Cancelar
            </a>
        </div>
        <!-- ./Card Footer-Buttons -->
    </form>


    <{% block javascript %}
        <script src="{% static 'padron/js/validations.js' %}"></script>
    {% endblock %}

{% endblock %}
<!-- ./Data Body -->

app/core/erp/templates/padron/list.html
{% extends 'list.html' %}

{% load static %}
<!-- Head List -->
{% block head_List %}
    <!-- DataTable - Botones -->
    <link rel="stylesheet" href="{% static 'librery/datatables-1.10.22/plugins/buttons-1.6.1/css/buttons.bootstrap.min.css' %}"/>
    <script src="{% static 'librery/datatables-1.10.22/plugins/buttons-1.6.1/js/dataTables.buttons.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'librery/datatables-1.10.22/plugins/jszip-2.5.0/jszip.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'librery/datatables-1.10.22/plugins/pdfmake-0.1.36/pdfmake.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'librery/datatables-1.10.22/plugins/pdfmake-0.1.36/vfs_fonts.js' %}" type="text/javascript"></script>
    <script src="{% static 'librery/datatables-1.10.22/plugins/buttons-1.6.1/js/buttons.html5.min.js' %}" type="text/javascript"></script>
    <!-- ./DataTable - Botones -->

    <script src="{% static 'padron/js/list.js' %}"></script>

{% endblock %}
<!-- ./Head List -->
<!-- Table -->
{% block columns %}
    <tr>
        <th class="th-sm">Acción</th>
        <th class="th-sm">DNI</th>
        <th class="th-sm">Apellidos</th>
        <th class="th-sm">Nombres</th>
        <th class="th-sm">Domicilio</th>
        <th class="th-sm">Departamento</th>
        <th class="th-sm">Código Circuito</th>
        <th class="th-sm">Nombre Circuito</th>
        <th class="th-sm">N° Mesa</th>
        <th class="th-sm">Voto</th>
    </tr>
{% endblock %}

{% block rows %}

{% endblock %}
<!-- ./Table -->
<!-- Footer-Buttons -->
{% block footer_buttons %}
    <div class="card-footer text-center">
        <a href="{{ padron_update }}" style="background-color:var(--green08); FONT-SIZE: 9pt"
           class="btn text-white btn-rounded"><i class="fa-solid fa-person-circle-question"></i> Votó</a>
{#            class="btn text-white btn-rounded"><i class="fa-solid fa-list-check"></i> Votó</a>#}
        <a href="{{ list_url }}" style="background-color:var(--green05); FONT-SIZE: 9pt"
           class="btn text-white btn-rounded"><i class="fa-solid fa-rotate"></i> Actualizar</a>
    </div>
{% endblock %}
<!-- ./Footer-Buttons -->
<!-- JavaScript -->
{% block javascript %}

{% endblock %}
<!-- ./JavaScript -->

app/core/erp/templates/padron/mesaupdate.html
{% extends 'body.html' %}

{% load static %}

{% load widget_tweaks %}
<!-- Extra Librerys -->
{% block head_extra %}
    <link rel="stylesheet" href="{% static 'librery/datatables-1.10.22/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'librery/datatables-1.10.22/plugins/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static 'librery/datatables-1.10.22/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'librery/datatables-1.10.22/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'librery/datatables-1.10.22/plugins/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'librery/datatables-1.10.22/plugins/js/responsive.bootstrap4.min.js' %}"></script>
    <!-- Head List -->
    <!-- JavaScript extra -->
    <script src="{% static 'padron/js/mesaupdate.js' %}"></script>
    <!-- JavaScript extra -->


{% endblock %}
<!-- ./Extra Librerys -->

<!-- Data Body -->
{% block data_body %}
    <!-- Card Header -->
    <form method="POST" action="." id="FormCreate" enctype="multipart/form-data">
        <div class="card-header card-primary card-outline">
            <h3 class="card-title">
                <i class="fa-solid fa-rotate"></i> {{ title }}
            </h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <!-- ./Card Header -->
        <!-- Card Body -->
        <div class="card-body">
            {% csrf_token %}
            <input type="hidden" name="action" value="{{ action }}">
            {% if form.errors %}
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="fa-solid fa-triangle-exclamation"></i> ! Ha ocurrido un ERROR !</h5>
                    <ul>
                        {% for field in form %}
                            {% for error in form %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

            <div class="row">
                <div class="col-lg-3">
                    <div class="input-group mb-3">

                        <div class="input-group mb-3">
                            <input id="id_search" name="search" type="text" class="form-control select2-blue" placeholder="Ingrese N° de Mesa..."
                                   aria-label="search_product" aria-describedby="button-addon2" autocomplete="off" minlength="1" maxlength="4">
                            <button style="background-color:var(--blue02); Font-size: 12px"
                                class="btn text-white btnSearchProduct" id="id_btnSearchProduct" name="btnSearchProduct">
                                <i class="fa-solid fa-magnifying-glass"></i> Buscar
                            </button>
                        </div>


                    </div>

                    <div class="form-outline">
                        <input id="id" name="id" type="number" style="display:none;" class="form-control"
                               aria-label="id"
                               aria-describedby="addon-wrapping">
                    </div>
                </div>
                <div class="col-lg-9"></div>
            </div>

            <button type="button" style="background-color:var(--orange01); Font-size: 12px"
                    class="btn text-white btn-rounded btnRemoveAll">
                <i class="fa-solid fa-trash-can"></i> Limpiar
            </button>
            <hr>

            <div class="row">
                <div class="col-lg-12">
                    <table id="tblPadron" class="table table-hover table-sm">
                        <thead style="background-color:var(--blue02);" class="text-white">
                        <tr>
{#                            <th>ID</th>#}
                            <th>Votó</th>
                            <th>DNI</th>
                            <th>Apellido</th>
                            <th>Nombre</th>
                            <th>Domicilio</th>
                            <th>Departamento</th>
                            <th>Nombre Circuito</th>
                            <th>Código Circuito</th>
                            <th>Mesa</th>
                        </tr>
                        </thead>
                        <tbody id="tableAllEvents">
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

        <!-- Card Footer-Buttons -->
        <div class="card-footer text-center">
            <button style="background-color:var(--green05); FONT-SIZE: 9pt"
                    class="btn text-white btn-rounded btnUpdateDNI btnUpdateDNIKeyup" type="submit" id="id_btnUpdateDNI" name="btnUpdateDNI">
                <i class="fa-solid fa-rotate"></i> Actualizar
            </button>
            <button type="button" id="cleanAll" style="background-color:var(--orange01); FONT-SIZE: 9pt"
                    class="btn text-white btn-rounded btnRemoveAll">
                <i class="fa-solid fa-trash-can"></i> Limpar
            </button>
            <a href="{% url 'app:padron_list' %}" style="background-color:var(--red06); FONT-SIZE: 9pt"
               class="btn text-white btn-rounded">
                <i class="fa-solid fa-xmark"></i> Cancelar
            </a>
        </div>
        <!-- ./Card Footer-Buttons -->
    </form>

    <!-- JavaScript -->
    {% block javascript %}
        <script src="{% static 'padron/js/validations.js' %}"></script>
    {% endblock %}
    <!-- ./JavaScript -->

{% endblock %}
<!-- ./Data Body -->