app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core.homepage.views import IndexView
from django.conf.urls import handler400
from core.erp.views.dashboard.views import page_not_found404

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('login/', include('core.login.urls')),
    path('user/', include('core.user.urls')),
    path('erp/', include('core.erp.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/core/erp/urls.py
from django.urls import path
from core.erp.views.padron.views import *
from core.erp.views.dninoexist.views import *
from core.erp.views.dashboard.views import *

app_name = 'app'

urlpatterns = [
    # PADRON
    path('padron/list/', PadronListView.as_view(), name='padron_list'),
    path('padron/update/<int:pk>/', PadronUpdateView.as_view(), name='padron_update'),
    path('padron/dniupdate/', PadronDNIUpdateView.as_view(), name='padron_dniupdate'),
    path('padron/mesaupdate/', PadronMesaDNIUpdateView.as_view(), name='padron_tableupdate'),

    # DNI no Existen
    path('dninoexist/list/', DniNoExistListView.as_view(), name='dninoexist_list'),
    path('dninoexist/create/', DniNoExistCreateView.as_view(), name='dninoexist_create'),
    path('dninoexist/update/<int:pk>/', DniNoExistUpdateView.as_view(), name='dninoexist_update'),
    path('dninoexist/delete/<int:pk>/', DniNoExistDeleteView.as_view(), name='dninoexist_delete'),

    # PANEL DASHBOARD
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
]

app/core/login/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from core.login.views import *

app_name = 'access'

urlpatterns = [
    # category
    path('', LoginFormView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # path('reset/password/', ResetPasswordView.as_view(), name='reset-password'),
    # path('change/password/<str:token>/', ChangePasswordView.as_view(), name='change-password')
]

app/core/homepage/models.py
from django.db import models

# Create your models here.

app/core/homepage/views.py
from django.views.generic import TemplateView

# Create your views here.
class IndexView(TemplateView):
    template_name = 'index.html'

app/core/homepage/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="data:,">

    <title>Elección</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
{#    <link href="{% static 'img/favicon.png' %}" rel="icon">#}
{#    <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">#}

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet">
    <!-- ./Google Fonts -->
    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <!-- ./Vendor CSS Files -->
    <!-- Fontawesome -->
    <link href="{% static 'librery/fontawesome-free-6.4.0/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'librery/fontawesome-free-6.4.0/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'librery/fontawesome-free-6.4.0/css/solid.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'librery/fontawesome-free-6.4.0/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'librery/fontawesome-free-6.4.0/js/fontawesome.js' %}"></script>
    <script src="{% static 'librery/fontawesome-free-6.4.0/js/solid.js' %}"></script>
    <script src="{% static 'librery/fontawesome-free-6.4.0/js/brands.js' %}"></script>
    <script src="{% static 'librery/fontawesome-free-6.4.0/js/all.min.js' %}"></script>
    <!-- ./Fontawesome -->

    <!-- Template Main CSS File -->
    <link href="{% static 'css/main.css' %}" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Nova
    * Updated: May 30 2023 with Bootstrap v5.3.0
    * Template URL: https://bootstrapmade.com/nova-bootstrap-business-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body class="page-index">

<!-- ======= Header ======= -->
<header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

        <a href="index.html" class="logo d-flex align-items-center"></a>

        <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
        <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

        <nav id="navbar" class="navbar">
            <ul>
                <li><a href="{% url 'index' %}" class="active"><i class="fa-solid fa-bars"></i></a></li>
                <li><a href="{% url 'app:dashboard' %}" class="active"><i class="fa-solid fa-house-flag"></i></a></li>
                <li><a href="{% url 'app:padron_list' %}"><i class="fa-solid fa-rectangle-list"></i></a></li>
                <li><a href="{% url 'app:padron_dniupdate' %}"><i class="fa-solid fa-person-circle-question"></i></a></li>
                <li><a href="{% url 'app:padron_tableupdate' %}"><i class="fa-solid fa-chalkboard-user"></i></a></li>
                <li><a href="{% url 'app:dninoexist_list' %}"><i class="fa-solid fa-id-card"></i></a></li>
                <li><a href="{% url 'access:logout' %}"><i class="fa-solid fa-right-from-bracket" aria-hidden="true"></i></a></li>
            </ul>
        </nav><!-- .navbar -->

    </div>
</header><!-- End Header -->

<!-- ======= Hero Section ======= -->
<section id="hero" class="hero d-flex align-items-center">
    <div class="container">
        <div class="row">
            <div class="col-xl-4">
                <h2 data-aos="fade-up">ELECCIONES</h2>
                <blockquote data-aos="fade-up" data-aos-delay="100">
                    <p>Bienvenido a nuestro sitio web de elección 2023. Aquí, tú eres el
                        protagonista.</p>
                    <p>#Elecciones - #TuEresProtagonista".</p>
                </blockquote>
                <div class="d-flex" data-aos="fade-up" data-aos-delay="200">
                    <a href="{% url 'access:login' %}" class="btn-get-started">Ingresar <i class="fa-solid fa-right-to-bracket"></i></a>
                </div>

            </div>
        </div>
    </div>
</section><!-- End Hero Section -->

<div id="preloader"></div>

<!-- Vendor JS Files -->
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'vendor/aos/aos.js' %}"></script>
<script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'vendor/php-email-form/validate.js' %}"></script>
<!-- ./Vendor JS Files -->
<!-- Template Main JS File -->
<script src="{% static 'js/main.js' %}"></script>

</body>

</html>