app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core.homepage.views import IndexView
from django.conf.urls import handler400
from core.erp.views.dashboard.views import page_not_found404

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('login/', include('core.login.urls')),
    path('user/', include('core.user.urls')),
    path('erp/', include('core.erp.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/core/erp/urls.py
from django.urls import path
from core.erp.views.padron.views import *
from core.erp.views.dninoexist.views import *
from core.erp.views.dashboard.views import *

app_name = 'app'

urlpatterns = [
    # PADRON
    path('padron/list/', PadronListView.as_view(), name='padron_list'),
    path('padron/update/<int:pk>/', PadronUpdateView.as_view(), name='padron_update'),
    path('padron/dniupdate/', PadronDNIUpdateView.as_view(), name='padron_dniupdate'),
    path('padron/mesaupdate/', PadronMesaDNIUpdateView.as_view(), name='padron_tableupdate'),

    # DNI no Existen
    path('dninoexist/list/', DniNoExistListView.as_view(), name='dninoexist_list'),
    path('dninoexist/create/', DniNoExistCreateView.as_view(), name='dninoexist_create'),
    path('dninoexist/update/<int:pk>/', DniNoExistUpdateView.as_view(), name='dninoexist_update'),
    path('dninoexist/delete/<int:pk>/', DniNoExistDeleteView.as_view(), name='dninoexist_delete'),

    # PANEL DASHBOARD
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
]

app/core/login/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from core.login.views import *

app_name = 'access'

urlpatterns = [
    # category
    path('', LoginFormView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # path('reset/password/', ResetPasswordView.as_view(), name='reset-password'),
    # path('change/password/<str:token>/', ChangePasswordView.as_view(), name='change-password')
]

app/core/user/urls.py
from django.urls import path

from core.user.views import *

app_name = 'user'

urlpatterns = [
    path('list/', UserListView.as_view(), name='user_list'),
    path('create/', UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    path('change/password/', UserChangePasswordView.as_view(), name='user_change_password'),
]

app/core/erp/views/dashboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse_lazy
from django.shortcuts import render


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        request.user.get_group_session()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['title'] = 'Reporte de ventas anual'
        context['list_url'] = reverse_lazy('app:padron_list')
        context['padron_url'] = reverse_lazy('app:padron_list')
        context['dni_no_url'] = reverse_lazy('app:dninoexist_list')
        context['padron_dni_update'] = reverse_lazy('app:padron_dniupdate')
        return context


# Paginas de ERRORES
def page_not_found404(request, exception):
    return render(request,'404.html')

app/templates/body.html
{% extends 'home.html' %}

{% load static %}

<!-- Body -->
{% block body %}
    <body class="hold-transition sidebar-mini sidebar-collapse layout-footer-fixed">
    <div class="wrapper">

        {% include 'navbar.html' %}

        {% include 'sidebar.html' %}

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">

            {% include 'contentheader.html' %}

            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-12">

                            <div class="card">

                                {% block data_body %}

                                {% endblock %}

                            </div>

                        </div>
                    </div>
                </div>
            </section>

        </div>

        {% include 'footer.html' %}

    </div>
    <!-- JavaScript -->
    {% block javascript %}

    {% endblock %}
    <!-- ./JavaScript -->
    <!-- Mensaje ERROR Permisos -->
    <script>
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}<br>';
            {% endfor %}
            html += '</p>';
            Swal.fire({
                title: 'Error!',
                html: html,
                icon: 'error'
            });
        {% endif %}
    </script>
    <!-- ./Mensaje ERROR Permisos -->
    </body>
{% endblock %}
<!-- ./Body -->

app/templates/contentheader.html
{% load static %}
<!-- APP Widgwt Tweaks -->
{% load widget_tweaks %}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Bienvenido <strong>{{ request.user.username }}</strong></h1>
{#                <h1>Bienvenido <strong>{{ request.user.get_full_name }}</strong></h1>#}
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a class="text-decoration-none" href="{% url 'app:padron_list' %}"><i class="fa-solid fa-rectangle-list"></i> Padrón</a></li>
                    <li class="breadcrumb-item"><a class="text-decoration-none" href="{% url 'app:padron_dniupdate' %}"><i class="fa-solid fa-person-circle-question"></i> NO Votó ?</a></li>
                    <li class="breadcrumb-item"><a class="text-decoration-none" href="{% url 'app:padron_tableupdate' %}"><i class="fa-solid fa-chalkboard-user"></i> Mesa</a></li>
                    <li class="breadcrumb-item"><a class="text-decoration-none" href="{% url 'app:dninoexist_list' %}"><i class="fa-solid fa-id-card"></i> DNI NO Encontrado</a></li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- /.content-header -->

app/templates/create.html
{% extends 'body.html' %}

{% load static %}
<!-- APP Widgwt Tweaks -->
{% load widget_tweaks %}

{% block head_extra %}
    {% block head_form %}

    {% endblock %}
{% endblock %}

<!-- Data Body -->
{% block data_body %}
    <!-- Card Header -->
    <form method="POST" action="." id="FormCreate" enctype="multipart/form-data">
        <div class="card-header card-primary card-outline">
            <h3 class="card-title">
                {% if action == 'create' %}
                    <i class="fa-solid fa-plus"></i>
                {% else %}
                    <i class="fa-solid fa-rotate"></i>
                {% endif %}
                {{ title }}
            </h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <!-- ./Card Header -->
        <!-- Card Body -->
        <div class="card-body">
            {% csrf_token %}
            <input type="hidden" name="action" value="{{ action }}">
            {% if form.errors %}
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="fa-solid fa-triangle-exclamation"></i> ! Ha ocurrido un ERROR !</h5>
                    <ul>
                        {% for field in form %}
                            {% for error in form %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            {% for field in form.visible_fields %}
                <label for="name">{{ field.label }}</label>
                {{ field|add_class:'form-control' }}
            {% endfor %}
        </div>
        <!-- ./Card Body -->
        <!-- Card Footer-Buttons -->
        <div class="card-footer text-center">
            {% if action == 'create' %}
                <button type="submit" style="background-color:var(--blue02); FONT-SIZE: 9pt"
                        class="btn text-white btn-rounded">
                    <i class="fa-solid fa-plus"></i> Crear
                </button>
                <button type="button" onclick="limpiarForm()" style="background-color:var(--orange01); FONT-SIZE: 9pt"
                        class="btn text-white btn-rounded">
                    <i class="fa-solid fa-trash-can"></i> Limpar
                </button>
            {% else %}
                <button type="submit" id="upDates" style="background-color:var(--green05); FONT-SIZE: 9pt"
                        class="btn text-white btn-rounded">
                    <i class="fa-solid fa-rotate"></i> Actualizar
                </button>
            {% endif %}
            <a href="{{ list_url }}" style="background-color:var(--red06); FONT-SIZE: 9pt"
               class="btn text-white btn-rounded">
                <i class="fa-solid fa-xmark"></i> Cancelar
            </a>
        </div>
        <!-- ./Card Footer-Buttons -->
    </form>

    <script>
        function limpiarForm() {
            document.getElementById("FormCreate").reset();
        }

        $('form').on('submit', function (e) {
            e.preventDefault();
            let dataForm = new FormData(this);
            alert_confirm(window.location.pathname, dataForm, 'Confirmar', '¿Estás seguro de realizar la siguiente Acción?', function () {
                location.href = '{{ list_url }}';
            });
        });

    </script>

{% endblock %}
<!-- ./Data Body -->

app/templates/dashboard.html
{% extends "body.html" %}

{% load static %}

{% block head_extra %}
    <style>
        img {
            max-width: 100%;
            display: block;
            width: 60%;
            margin: auto;
        }
    </style>

{% endblock %}


{% block data_body %}

    <sec class="card-body dashboard-card-body">
        <img src="{% static 'image/img-dashboard.png' %}" alt="">
    </sec>
    <!-- Footer-Buttons -->
    {% block footer_buttons %}

    {% endblock %}
    <!-- ./Footer-Buttons -->

{% endblock %}

app/templates/delete.html
{% extends 'body.html' %}

{% load static %}

{% load widget_tweaks %}

<!-- Data Body -->
{% block data_body %}
    <!-- Card Header -->
    <form method="POST" action="." enctype="multipart/form-data">

        <div class="card card-danger card-outline">
            <div class="card-header">
                <h3 class="card-title" style="color:var(--red02);">
                    <i class="fas fa-solid fa-trash-can"></i>
                    {{ title }}
                </h3>
            </div>
        </div>
        <div class="card-body">
            {% csrf_token %}
            <input type="hidden" name="action" value="{{ action }}">
            {% if form.errors %}
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="fa-solid fa-triangle-exclamation"></i>
                        ¡Ha ocurrido un ERROR al intentar Eliminar el registro!
                    </h5>
                </div>
            {% endif %}
            <div class="alert text-white" style="background-color:var(--red02);">
                <h5><strong><i class="fa-solid fa-triangle-exclamation"></i> Notificación!</strong></h5>
                ¿Estás seguro de eliminar el registro: <strong> {{ object.id }} </strong>? Si confirma la eliminación,
                no podrá acceder nuevamente a este Registro nuevamente.
            </div>
        </div>
        <div class="card-footer text-center">
            <button type="submit" style="background-color:var(--red02); FONT-SIZE: 9pt"
                    class="btn text-white btn-rounded">
                <i class="fa-solid fa-trash-can sm-1"></i> Confirmar
            </button>
            <a href="{{ list_url }}" style="background-color:var(--red06); FONT-SIZE: 9pt"
               class="btn text-white btn-rounded">
                <i class="fa-solid fa-xmark ml-1"></i> Cancelar
            </a>
        </div>
    </form>

    <script>
        $('form').on('submit', function (e) {
            e.preventDefault();
            let parameters = new FormData(this);
            alert_confirm(window.location.pathname, parameters, 'Notificación', '¿Estas seguro de eliminar el siguiente Registro?', function () {
                Swal.fire({
                    title: 'Alerta',
                    text: 'Registro eliminado con Éxito',
                    icon: 'success',
                    timer: 2000,
                    onClose: () => {
                        location.href = '{{ list_url }}';
                    }
                }).then((result) => {

                });
            });
        });
    </script>

{% endblock %}
<!-- ./Data Body -->


{#$('form').on('submit', function (e) {#}
{#            e.preventDefault();#}
{#            $.ajax({#}
{#                url: window.location.pathname,#}
{#                type: 'POST',#}
{#                data: {},#}
{#                datatype: 'json'#}
{#            }).done(function (data) {#}
{#                if (!data.hasOwnProperty('error')) {#}
{#                    location.href = '{{ list_url }}';#}
{#                    return false;#}
{#                }#}
{#                message_error(data.error);#}
{#            }).fail(function (jqXHR, textStatus, errorThrawn) {#}
{#                alert(textStatus + ' - ' + errorThrawn);#}
{#            }).always(function (data) {#}
{##}
{#            });#}
{#        });#}

app/templates/footer.html
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        <strong>Elecciones 2023</strong>
    </div>
    <!-- Default to the left -->
    <strong>Elecciones 2023 <a href="#"></a></strong>
</footer>

app/templates/home.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="data:,">
    <title>{{ title }}</title>
    <!-- Bootstrap -->
    <link href="{% static 'librery/bootstrap-5.3.0/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'librery/bootstrap-5.3.0/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'librery/bootstrap-5.3.0/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'librery/bootstrap-5.3.0/js/popper.min.js' %}"></script>
    <!-- ./Bootstrap -->
    <!-- AdminLTE3 -->
{#    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">#}
    <link rel="stylesheet" href="{% static 'librery/AdminLTE-3.2.0/plugins/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'librery/AdminLTE-3.2.0/dist/css/adminlte.min.css' %}">
    <script src="{% static 'librery/AdminLTE-3.2.0/plugins/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'librery/AdminLTE-3.2.0/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'librery/AdminLTE-3.2.0/dist/js/adminlte.min.js' %}"></script>
    <!-- ./AdminLTE3 -->
    <!-- Fontawesome -->
    {#    <script src="https://kit.fontawesome.com/606bbbad74.js" crossorigin="anonymous"></script>#}
    <link href="{% static 'librery/fontawesome-free-6.4.0/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'librery/fontawesome-free-6.4.0/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'librery/fontawesome-free-6.4.0/css/solid.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'librery/fontawesome-free-6.4.0/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'librery/fontawesome-free-6.4.0/js/fontawesome.js' %}"></script>
    <script src="{% static 'librery/fontawesome-free-6.4.0/js/solid.js' %}"></script>
    <script src="{% static 'librery/fontawesome-free-6.4.0/js/brands.js' %}"></script>
    <script src="{% static 'librery/fontawesome-free-6.4.0/js/all.min.js' %}"></script>
    <!-- ./Fontawesome -->
    <!-- Font Google -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
    <!-- ./Font Google -->
    <!-- Sweetalert2 -->
    <script src="{% static 'librery/sweetalert2/sweetalert2.min.css' %}"></script>
    <script src="{% static 'librery/sweetalert2/sweetalert2.all.min.js' %}"></script>
    <script src="{% static 'librery/sweetalert2/sweetalert2.min.js' %}"></script>
    <!-- ./Sweetalert2 -->
    <!-- Jquery-Confirm (Alert) -->
    <link rel="stylesheet" href="{% static 'librery/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}">
    <script src="{% static 'librery/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>
    <!-- Jquery-Confirm (Alert) -->
    <!-- My CSS & Functions -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/functions.js' %}"></script>
    <!-- ./My CSS & Functions -->
    <!-- Extra Head -->
    {% block head_extra %}

    {% endblock %}
    <!-- ./Extra Head -->
</head>

<!-- Body -->
{% block body %}

{% endblock %}
<!-- ./Body -->

</html>

app/templates/navbar.html
{% load static %}
<!-- APP Widgwt Tweaks -->
{% load widget_tweaks %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            {#            <a href="../../index3.html" class="nav-link">Home</a>#}
            <a href="{% url 'index' %}" class="nav-link">Home</a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">

        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fa-solid fa-building-flag"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <div class="dropdown-divider"></div>
                <a href="{% url 'app:padron_list' %}" class="dropdown-item">
                    <i class="fa-solid fa-rectangle-list mr-2"></i> Padrón
                </a>

                <div class="dropdown-divider"></div>
                <a href="{% url 'app:padron_dniupdate' %}" class="dropdown-item">
                    <i class="fa-solid fa-person-circle-question mr-2"></i> NO Votó ?
                </a>

                <div class="dropdown-divider"></div>
                <a href="{% url 'app:padron_tableupdate' %}" class="dropdown-item">
                    <i class="fa-solid fa-chalkboard-user"></i> Mesa
                </a>

                <div class="dropdown-divider"></div>
                <a href="{% url 'app:dninoexist_list' %}" class="dropdown-item">
                    <i class="fa-solid fa-id-card mr-2"></i> DNI NO Encontrados
                </a>
            </div>
        </li>


        <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">

            {% if request.user.groups.all %}
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link {% if request.user.groups.all.count > 1 %} dropdown-toggle {% endif %}">{{ request.session.group }}</a>
                    {% if request.user.groups.all.count > 1 %}
                        <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow"
                            style="left: 0px; right: inherit;">
                            {% for g in request.user.groups.all %}
                                {% if g.id != request.session.group.id %}
                                    <li><a href="{% url 'user:user_change_group' g.id %}"
                                           class="dropdown-item">{{ g.name }} </a></li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    {% endif %}
                </li>
            {% endif %}

            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="fa-solid fa-user-gear"></i> {{ request.user.username }}
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <span class="dropdown-header" style="font-size: 12px;">
                            Su último acceso fue {{ request.user.last_login }}
                        </span>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'user:user_profile' %}" class="dropdown-item">
                        <i class="fa-solid fa-user-pen mr-2"></i> Editar Perfil
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'user:user_change_password' %}" class="dropdown-item">
                        <i class="fa-solid fa-user-lock mr-2"></i> Cambiar Password
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">
                        <p>El sistema está preparado para realizar diferentes acciones</p>
                    </a>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'access:logout' %}">
                    <i class="fa-solid fa-right-from-bracket" aria-hidden="true"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                    <i class="fas fa-expand-arrows-alt"></i>
                </a>
            </li>

        </ul>

        <!-- Navbar Search -->
        <!-- Notifications Dropdown Menu -->
        {#        <li class="nav-item dropdown">#}
        {#            <a class="nav-link" data-toggle="dropdown" href="#">#}
        {#                <i class="far fa-bell"></i>#}
        {#                <span class="badge badge-warning navbar-badge">15</span>#}
        {#            </a>#}
        {#            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">#}
        {#                <span class="dropdown-item dropdown-header">15 Notifications</span>#}
        {#                <div class="dropdown-divider"></div>#}
        {#                <a href="#" class="dropdown-item">#}
        {#                    <i class="fas fa-envelope mr-2"></i> 4 new messages#}
        {#                    <span class="float-right text-muted text-sm">3 mins</span>#}
        {#                </a>#}
        {#                <div class="dropdown-divider"></div>#}
        {#                <a href="#" class="dropdown-item">#}
        {#                    <i class="fas fa-users mr-2"></i> 8 friend requests#}
        {#                    <span class="float-right text-muted text-sm">12 hours</span>#}
        {#                </a>#}
        {#                <div class="dropdown-divider"></div>#}
        {#                <a href="#" class="dropdown-item">#}
        {#                    <i class="fas fa-file mr-2"></i> 3 new reports#}
        {#                    <span class="float-right text-muted text-sm">2 days</span>#}
        {#                </a>#}
        {#                <div class="dropdown-divider"></div>#}
        {#                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>#}
        {#            </div>#}
        {#        </li>#}
        {#        <li class="nav-item">#}
        {#            <a class="nav-link" data-widget="fullscreen" href="#" role="button">#}
        {#                <i class="fas fa-expand-arrows-alt"></i>#}
        {#            </a>#}
        {#        </li>#}

    </ul>
</nav>
<!-- /.navbar -->

app/templates/sidebar.html
{% load static %}
<!-- APP Widgwt Tweaks -->
{% load widget_tweaks %}
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        {#  <a href="../../index3.html" class="brand-link">#}
        <img src="{% static 'image/voto.png' %}" alt="Logo" class="brand-image img-circle elevation-3"
             style="opacity: .8">
        {#    <img src="../../dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">#}
        <span class="brand-text font-weight-light">Elecciones</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                {#                <img src="#" class="img-circle elevation-2" alt="User Image">#}
                <img src="{{ request.user.get_image }}" class="img-circle elevation-2" alt="User Image">
                {#            <img src="../../dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">#}
            </div>
            <div class="info">
                {#                <a href="#" class="d-block">{{ request.user.get_full_name }}</a>#}
                <a href="#" class="d-block">{{ request.user.username }}</a>
            </div>
        </div>

        <!-- SidebarSearch Form -->
        {#        <div class="form-inline">#}
        {#            <div class="input-group" data-widget="sidebar-search">#}
        {#                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">#}
        {#                <div class="input-group-append">#}
        {#                    <button class="btn btn-sidebar">#}
        {#                        <i class="fas fa-search fa-fw"></i>#}
        {#                    </button>#}
        {#                </div>#}
        {#            </div>#}
        {#        </div>#}

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column nav-legacy nav-child-indent" data-widget="treeview"
                role="menu" data-accordion="false">

                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">

                        <i class="nav-icon fa-solid fa-building-flag"></i>
                        <p> Acciones <i class="right fa-solid fa-angle-left"></i></p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                        <li class="nav-item">
                            <a href="{% url 'app:padron_list' %}" class="nav-link">
                                <i class="nav-icon fa-solid fa-rectangle-list"></i>
                                <p> Padrón</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'app:padron_dniupdate' %}" class="nav-link">
                                <i class="nav-icon fa-solid fa-person-circle-question"></i>
                                <p> NO Votó ?</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'app:padron_tableupdate' %}" class="nav-link">
                                <i class="nav-icon fa-solid fa-chalkboard-user"></i>
                                <p> Mesa</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'app:dninoexist_list' %}" class="nav-link">
                                <i class="nav-icon fa-solid fa-id-card"></i>
                                <p> DNI NO Encontrados</p>
                            </a>
                        </li>

                    </ul>
                </li>

            </ul>

            <ul class="nav nav-pills nav-sidebar flex-column nav-legacy nav-child-indent" data-widget="treeview"
                role="menu" data-accordion="false">

                <li class="nav-item has-treeview">
                    <a href="{% url 'user:user_list' %}" class="nav-link">
                        <i class="nav-icon fa-solid fa-user-group"></i>
                        <p> Usuarios </p>
                    </a>
                </li>

            </ul>

            <ul class="nav nav-pills nav-sidebar flex-column nav-legacy nav-child-indent" data-widget="treeview"
                role="menu" data-accordion="false">

                <li class="nav-item has-treeview">
                    <a href="{% url 'access:logout' %}" class="nav-link">
                        <i class="nav-icon fa-solid fa-right-from-bracket"></i>
                        <p> Cerrar Sesión </p>
                    </a>
                </li>

            </ul>

        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>